# Generated by Django 5.0.2 on 2024-02-21 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="full_name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
